{% set version = "3.4.2" %}

package:
  name: r
  version: {{ version }}

build:
  number: 0

requirements:
  run:
    - r-base {{ version }}
    - r-recommended {{ version }}

about:
  home: http://www.r-project.org/
  license: GPL-3.0
  summary: 'R is a free software environment for statistical computing and graphics.'

extra:
  recipe-maintainers:
    - bgruening
    - johanneskoester
    - mingwandroid
