travis:
  secure:
    BINSTAR_TOKEN: Iq4gPmcsMUIo6tVWYLQFYbMYB+YiYItC8z/T4c166j/ktRX5Lu7MmyJ9MXdsQ7mcdPWO4JLnHJi0Spvk+1LKKhu3vL1g3LeV4qkCCsHzewBUDjCmoCkwNhZdBtM3kOtWLZqXFGShuY06np2MwRJrBwPJ7qCDfG2zqdLJ/Aq+sS2QTHdPZAcHV+lnDIlnzqJ0smUiYhN+nvz1BrT2I1gndO5kIy/BnZJ21HUBnUPLfXoN9usjmW3DqD2fo+rjqkdGP1a39dExVVLUuS3sywESPCxmv785K04hN2WMzziKbG9ABgEBZlcd6YT2roYaoQP+NeCp4de/l0PvbummGEKxcvihWncqYmWvs3C9PCSSGYZun/O+ZA6SyGniH5oLwG8e9lI3FEHoynmNVGLb6GLAHbr3aV0rYoRkS+hZJLSBpetqEaB+CLWQibCEDpmiPz7oSvdCsl4/DxXBRjyBowpVGdBITDg3SbhktgH1i5ZubzpjxgxIMUlM76Ha3J6DSOT10t5VmbF6uM0eP+pxEvzWQKYX7zZAqQKGj2FhVGocLHZaUpgeBLn99YOPmONs2shB8THv/f+ZbB10ovfcMlsl9kijJeZEbhVhfkdPZVczGMqrAcMGFjRZuZ/LFxIg3Ki8B4lm8lzJhmTGJ+AVGrfCOA4wKw+3B8car/a3iI4TMOU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
